import { MessageAssignmentEnum } from "../../atoms/tag";
import { SessionEnum } from "../../molecules/card/MessageCard";

export const DUMMY_CHAT = [
  {
    id: 1,
    name: "Mary Jane",
    date: "Today, 08:12",
    lastChat: "Ready ga gan barangnya kalo dikirim detik ini juga?",
    unreadChatCount: 1,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.waiting,
    session: SessionEnum["open"],
    isReplied: false,
  },
  {
    id: 2,
    name: "Mary Jane",
    date: "Today, 06:02",
    lastChat: "Hi Kak, barangnya ready silahkan di order ya!",
    unreadChatCount: 0,
    tag: "order, gundam, mainan anak,order, gundam, mainan anak",
    status: MessageAssignmentEnum.resolved,
    session: SessionEnum["open"],
    isReplied: true,
  },
  {
    id: 3,
    name: "Mary Jane",
    date: "Yesterday, 08:01",
    lastChat: "Hi Min, barang ini ready ga ya?",
    unreadChatCount: 2,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.assigned,
    session: SessionEnum["expiring"],
    isReplied: false,
  },
  {
    id: 4,
    name: "Mahmud Samrudi Wijaya Kusuma Adiningrat",
    date: "15 Oct 2022, 14:32",
    lastChat: "Kode OTP Anda untuk menggunakan WiFi@Matahari adalah 9437.",
    unreadChatCount: 0,
    tag: null,
    status: MessageAssignmentEnum.campaign,
    session: SessionEnum["expired"],
    isReplied: true,
  },
  {
    id: 5,
    name: "Mary Jane",
    date: "Today, 06:02",
    lastChat: "Terima kasih kak, ditunggu orderan selanjutnya",
    unreadChatCount: 0,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.assigned_to_me,
    session: SessionEnum["open"],
    isReplied: true,
  },
  {
    id: 10,
    name: "Mary Jane",
    date: "Today, 08:12",
    lastChat: "Ready ga gan barangnya kalo dikirim detik ini juga?",
    unreadChatCount: 1,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.waiting,
    session: SessionEnum["open"],
    isReplied: false,
  },
  {
    id: 20,
    name: "Mary Jane",
    date: "Today, 06:02",
    lastChat: "Hi Kak, barangnya ready silahkan di order ya!",
    unreadChatCount: 0,
    tag: "order, gundam, mainan anak,order, gundam, mainan anak",
    status: MessageAssignmentEnum.resolved,
    session: SessionEnum["open"],
    isReplied: true,
  },
  {
    id: 30,
    name: "Mary Jane",
    date: "Yesterday, 08:01",
    lastChat: "Hi Min, barang ini ready ga ya?",
    unreadChatCount: 2,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.assigned,
    session: SessionEnum["expiring"],
    isReplied: false,
  },
  {
    id: 40,
    name: "Mahmud Samrudi Wijaya Kusuma Adiningrat",
    date: "15 Oct 2022, 14:32",
    lastChat: "Kode OTP Anda untuk menggunakan WiFi@Matahari adalah 9437.",
    unreadChatCount: 0,
    tag: null,
    status: MessageAssignmentEnum.campaign,
    session: SessionEnum["expired"],
    isReplied: true,
  },
  {
    id: 50,
    name: "Mary Jane",
    date: "Today, 06:02",
    lastChat: "Terima kasih kak, ditunggu orderan selanjutnya",
    unreadChatCount: 0,
    tag: "order, gundam, mainan anak",
    status: MessageAssignmentEnum.assigned_to_me,
    session: SessionEnum["open"],
    isReplied: true,
  },
];
